In [1]:
import tensorflow as tf

## Let's see how to define different tensors

In [4]:
strings = tf.Variable("This is a string", tf.string)
intergers = tf.Variable(108, tf.int16)
floating = tf.Variable(69.69, tf.float64)

## Rank/Degree of Tensors

In [6]:
# Rank/Degree 0 Tensor
rank0_tensor = tf.Variable("Rank 0 Tensor", tf.string)

In [7]:
tf.rank(rank0_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [10]:
# Rank/Degree 1 Tensor
rank1_tensor = tf.Variable(["Rank 1 Tensor"], ["Rank 1 Tesnor"], tf.string)

In [11]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [12]:
# Rank/Degree 2 Tensor
rank2_tensor = tf.Variable([["Rank 2 Tensor"],["Rank 2 Tensor"]], tf.string)

In [13]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [16]:
# And so on...

## Changing shape

In [20]:
shape1 = tf.ones([1,2,3])

In [21]:
print(shape1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [23]:
# Here,
# 1 --> single list
# 2 --> two rows
# 3 --> three columns
# i.e., (2x3) matrix

In [24]:
reshape1 = tf.reshape(shape1, [3,2,1])

In [25]:
print(reshape1)

tf.Tensor(
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]], shape=(3, 2, 1), dtype=float32)


In [31]:
reshape2 = tf.reshape(shape1, [3, -1])

In [32]:
print(reshape2)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
